configVersion: 1.1

Items:
  page1:
    0:
      enabled: true
      material: GOLDEN_HELMET
      displayName: '&cGWツール分解'
      lore: 'CommonLore'
      enchanted: true
      model: 0
      resultItems:
        - isMythicItem: true
          mmid: '2025_GW_event_items_GWチケット'
          displayName: '&6&lGW&e&lチケット'
          amount: 16
        - isMythicItem: false
          type: GOLD_INGOT
          displayName: '&f金インゴット'
          amount: 16
      requiredItems:
        - isMythic: true
          mmid: '2025_GW_event_items_GWショベル10S'
          displayName: '&6GWショベル'
          amount: 1
        - isMythic: false
          type: DIAMOND_BLOCK
          displayName: '&fダイヤモンドブロック'
          amount: 64
    1:
      enabled: true
      material: SPONGE
      displayName: '&eスポンジ'
      lore: 'CommonLore'
      enchanted: false
      model: 0
      resultItems:
        - isMythicItem: false
          type: SPONGE
          displayName: '&fスポンジ'
          amount: 1
      requiredItems:
        - isMythic: false
          type: YELLOW_DYE
          displayName: '&f黄色の染料'
          amount: 4
        - isMythic: false
          type: GRAVEL
          displayName: '&f砂利'
          amount: 2
        - isMythic: false
          type: SAND
          displayName: '&f砂'
          amount: 2
        - isMythic: false
          type: HAY_BLOCK
          displayName: '&f俵'
          amount: 1
