configVersion: 1.2

Items:
  page1:
    0:
      enabled: true
      material: GOLDEN_HELMET
      displayName: '&cGWツール分解'
      lore: 'CommonLore'
      enchanted: true
      model: 0
      requiredItems:
        - isMythicItem: true
          mmid: '2025_GW_event_items_GWショベル10S'
          displayName: '&6GWショベル'
          amount: 1
        - isMythicItem: false
          type: DIAMOND_BLOCK
          displayName: '&fダイヤモンドブロック'
          amount: 64
      resultItems:
        - isMythicItem: true
          mmid: '2025_GW_event_items_GWチケット'
          displayName: '&6&lGW&e&lチケット'
          amount: 16
        - isMythicItem: false
          type: GOLD_INGOT
          displayName: '&f金インゴット'
          amount: 16
    1:
      enabled: true
      material: SPONGE
      displayName: '&eすっごいスポンジ&c(偽物)'
      lore: 'CommonLore'
      enchanted: false
      model: 0
      requiredItems:
        - isMythicItem: false
          type: YELLOW_DYE
          displayName: '&e黄色の染料'
          amount: 4
        - isMythicItem: false
          type: GRAVEL
          displayName: '&f砂利'
          amount: 2
        - isMythicItem: false
          type: SAND
          displayName: '&f砂'
          amount: 2
        - isMythicItem: false
          type: HAY_BLOCK
          displayName: '&f俵'
          amount: 1
      resultItems:
        - isMythicItem: false
          type: SPONGE
          displayName: '&fスポンジ'
          amount: 1


Lores:
  CommonLore:
    - '&f左クリックで1回変換します'
    - '&f右クリっくで上限まで変換します'
    - ''
  need9:
    - '&f圧縮に必要な数: &a9'
