name: CraftGuiExtension
version: '${project.version}'
main: net.azisaba.life.CraftGUIExtension
api-version: '1.15'
authors: [ albardoo02 ]
depend:
  - ItemStash
  - MMLuck
description: Configでアイテムを設定できるCraftGUI
website: https://github.com/albardoo02/CraftGUIExtension
commands:
  craftgui:
    aliases:
      - rgui
      - /rgui
      - ragui
      - /ragui
      - craft
      - /craft

permissions:
  craftguiextension.reload:
    default: op
  craftguiextension.register:
    default: op