name: CraftGuiExtension
version: '${project.version}'
main: net.azisaba.life.CraftGUIExtension
api-version: '1.15'
authors: [albardoo02]
description: Editable CraftGUI
website: https://github.com/albardoo02/CraftGUIExtension
softdepend:
  - StorageBox
commands:
  raggui:
    aliases:
      - assyuku
      - compress
      - ragggui
      - ragguui
      - ragui
      - raguiyan
      - ragunarok
      - rgui
      - ragusugi