name: CraftGuiExtension
version: '${project.version}'
main: net.azisaba.life.CraftGUIExtension
api-version: '1.15'
authors: [ albardoo02 ]
softdepend:
  - ItemStash
  - MMLuck
description: Configでアイテムを設定できるCraftGUI
website: https://github.com/albardoo02/CraftGUIExtension
commands:
  craftgui:
    aliases:
      - assyuku
      - compress
      - ragggui
      - ragguui
      - ragui
      - raguiyan
      - ragunarok
      - rgui
      - ragusugi
      - /rgui
      - /ragui